---
version: 2
jobs:
  build:
    docker: 
     - image: felicianotech/docker-hugo:0.47.1
    working_directory: /hugo
    environment: 
      HUGO_BUILD_DIR: /hugo/public
    steps:
     - checkout
     - run:
        name: "Run Hugo"
        command: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR --enableGitInfo --verbose --debug
     - run:
          name: Install AWS CLI 
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
            aws s3 sync s3://sandboxworms-proj5-102018 --sse=aws:kms --sse-kms-key-id ec0a605d-17e9-4ac8-a2e3-e299c1ee1a93   